import { FormEvent, useEffect, useRef, useState } from 'react'
import { Activity, BrainCircuit, Check, ChevronRight, FileText, LockKeyhole, Mic, MicOff, Monitor, Network, Phone, Plus, Radio, Send, ShieldCheck, Sparkles } from 'lucide-react'

const API = import.meta.env.VITE_ASTRA_API ?? 'http://localhost:8000'
type Task = { id:string; prompt:string; status:string; result?:string; confirmation_token?:string; created_at:string }
type Memory = { id:string; content:string; kind:string; created_at:string }
type Audit = { id:string; category:string; action:string; permission:string; timestamp:string }
const modules = [[Mic,'Voice system','Wake word · STT · TTS'],[BrainCircuit,'AI brain','Reasoning · planning'],[Monitor,'Computer','Windows · apps'],[Phone,'Phone','Android · calls'],[Network,'Browser','Search · APIs'],[FileText,'Files','Docs · PDFs'],[ShieldCheck,'Security','Policies · audit']]

export default function App() {
 const [online,setOnline]=useState(false), [prompt,setPrompt]=useState(''), [tasks,setTasks]=useState<Task[]>([]), [memories,setMemories]=useState<Memory[]>([]), [audit,setAudit]=useState<Audit[]>([]), [listening,setListening]=useState(false), [notice,setNotice]=useState('')
 const recognitionRef=useRef<any>(null)
 const load=async()=>{ try { const [h,t,m,a]=await Promise.all([fetch(`${API}/health`),fetch(`${API}/tasks`),fetch(`${API}/memory`),fetch(`${API}/audit`)]); setOnline(h.ok); setTasks(await t.json()); setMemories(await m.json()); setAudit(await a.json()) } catch {setOnline(false)} }
 useEffect(()=>{load(); const i=setInterval(load,7000); return()=>clearInterval(i)},[])
 const sendTask=async(text:string)=>{if(!text.trim())return; try { const res=await fetch(`${API}/tasks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:text})}); if(!res.ok)throw new Error(); const task:Task=await res.json(); setPrompt(''); setNotice('ASTRA completed your request.'); load(); speak(task.result || 'Your task has been completed.'); } catch {setNotice('ASTRA cannot reach its local agent core. Check that port 8001 is running.')}}
 const submit=async(e:FormEvent)=>{e.preventDefault(); await sendTask(prompt)}
 const speak=(text:string)=>{speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text))}
 const voice=()=>{ if(listening){recognitionRef.current?.stop(); return}; const Recognition=(window as any).webkitSpeechRecognition || (window as any).SpeechRecognition; if(!Recognition){setNotice('Speech recognition needs Chrome or Microsoft Edge. Open this URL in either browser and allow microphone access.');return}; const r=new Recognition(); recognitionRef.current=r; r.lang='en-US'; r.interimResults=true; r.continuous=false; r.onstart=()=>{setListening(true);setNotice('Listening… say a task for ASTRA.')}; r.onerror=(e:any)=>{setListening(false); setNotice(e.error==='not-allowed' ? 'Microphone permission was denied. Use the address-bar lock icon to allow it, then retry.' : `Voice input error: ${e.error}.`) }; r.onend=()=>setListening(false); r.onresult=(e:any)=>{const transcript=Array.from(e.results as any).map((result:any)=>result[0].transcript).join('');setPrompt(transcript); if(e.results[e.results.length-1].isFinal){setNotice(`Heard: “${transcript}” — sending to ASTRA.`);sendTask(transcript)}}; r.start() }
 const saveMemory=async()=>{const content=window.prompt('What should ASTRA remember?'); if(content){await fetch(`${API}/memory`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,kind:'note'})});load()}}
 return <main>
  <aside><div className="brand"><Sparkles/> <span>ASTRA</span><small>AI AGENT OS</small></div><nav><a className="active"><Activity/> Command center</a><a><BrainCircuit/> Agent engine</a><a><FileText/> Memory</a><a><ShieldCheck/> Security</a></nav><div className="side-status"><span className={online?'dot online':'dot'}/>{online?'Core systems online':'Core offline'}<small>Local-first control plane</small></div></aside>
  <section className="workspace"><header><div><p className="eyebrow">SYSTEM OVERVIEW</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}.</h1><p className="muted">What would you like ASTRA to handle?</p></div><div className="secure"><LockKeyhole/> Policy layer active</div></header>
   <form className="composer" onSubmit={submit}><button type="button" className={listening?'listen':''} onClick={voice} aria-label="Voice input">{listening?<MicOff/>:<Mic/>}</button><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask ASTRA to research, organize, or take a task…"/><button className="send" aria-label="Send"><Send/></button></form>{notice&&<p className="notice">{notice}</p>}
   <div className="grid">{modules.map(([Icon,name,detail]:any)=><article className="module" key={name}><Icon/><div><strong>{name}</strong><span>{detail}</span></div><ChevronRight/></article>)}</div>
   <div className="panels"><section className="panel tasks"><div className="panel-head"><div><p className="eyebrow">AGENT ENGINE</p><h2>Task monitor</h2></div><button onClick={load}>Refresh</button></div>{tasks.length?tasks.slice(0,4).map(t=><div className="task" key={t.id}><span className={`state ${t.status}`}/><div><strong>{t.prompt}</strong><small>{t.result}</small></div><button title="Read result" onClick={()=>speak(t.result||t.prompt)}><Radio/></button></div>):<div className="empty">No tasks yet. Give ASTRA its first objective.</div>}</section>
   <section className="panel memory"><div className="panel-head"><div><p className="eyebrow">CONTEXT</p><h2>Long-term memory</h2></div><button className="add" onClick={saveMemory}><Plus/> Remember</button></div>{memories.length?memories.slice(0,3).map(m=><div className="memory-item" key={m.id}><span>{m.kind}</span>{m.content}</div>):<div className="empty">No saved memories.</div>}</section></div>
   <section className="panel audit"><div className="panel-head"><div><p className="eyebrow">SECURITY</p><h2>Recent audit trail</h2></div><ShieldCheck/></div>{audit.length?audit.slice(0,4).map(a=><div className="audit-row" key={a.id}><span className={`pill ${a.permission}`}>{a.permission}</span><span>{a.category} / {a.action}</span><time>{new Date(a.timestamp).toLocaleTimeString()}</time></div>):<div className="empty">Every policy decision will appear here.</div>}</section>
  </section>
 </main>
}
